name: "coverage"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    name: "coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Code Coverage
        id: coverage
        if: github.event_name == 'pull_request'
        run: make coverage
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          COVERAGE: "coverage\n${{ steps.coverage.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Code Test Coverage 🖌\`${steps.coverage.outcome }}\`

            <details><summary>Coverage</summary>

            \`\`\`\n
            ${process.env.COVERAGE}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Coverage Status
        if: steps.coverage.outcome == 'failure'
        run: exit 1

