name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: "us-west-2"

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout@v2

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::689472803903:role/GitHubActions-Terraform-AWS-Lambda-Helper
          role-session-name: githubactions
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -var='environment=dev' -var='lambda_name=cron-lambda' -var='handler_name=handler' -var='region=us-west-2' -var='cron-minutes=25' -var='cron-hours=06' -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -auto-approve

